services:
  database:
    image: postgres:15.4-alpine
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_USER_FILE=/run/secrets/user
      - POSTGRES_PASSWORD_FILE=/run/secrets/password
      - POSTGRES_DB_FILE=/run/secrets/database
    networks:
      - sonar
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - database
      - user
      - password
volumes:
  postgres:
secrets:
    database:
        file: db_name.priv
    user:
        file: db_user.priv
    password:
        file: db_pass.priv
networks:
  sonar:
    external: true