ersion: "3.8"

services:

  traefik:
    image: traefik:latest

    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"

    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /root/traefik/acme.json:/acme.json

    networks:
      - reverse-proxy

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.traefik.rule=Host(`traefik.devalejandro.com`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal"  # ya lo tienes
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=alejandro:$$apr1$$D.MR7IIc$$PIf7Xe111wYCo6kOHDSaw/"
        - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}"
networks:
  reverse-proxy:
    external: true
