services:
  whoami:
    image: traefik/whoami
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
networks:
  traefik-net:
    external: true