services:
  backend:
    image: quotes-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
  postgres:
    image: postgres:13
    expose:
      - 5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=quotes
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: